# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name : Install Dependencies
      working-directory : ./mockServer
      run: npm install
    - name : RUN FIle INDEX.JS
      working-directory : ./mockServer
      run : nohup node index.js &
    - name: Build
      working-directory: ./MyLibrary
      run: swift build -v
    - name: Run tests
      working-directory: ./MyLibrary
      run: swift test -v
     

