# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x, 16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
          node-version: ${{ matrix.node-version }}
    - name: Build
      working-directory: ./MyLibrary
      run: swift build -v
    - name : INSTALL DEPENDECIES
      run : npm install
      working-directory: ./MyLibrary/mockServer
    - name : RUN FIle INDEX.JS
      working-directory : ./MyLibrary/mockServer
      run : node index.js
    - name: Run tests
      working-directory: ./MyLibrary
      run: swift test -v
     

